<?php
/**
 * ModelEmptyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BlockMarkets
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BlockMarkets Cryptocurrency API
 *
 * The BlockMarkets API provides real-time and historical market data on cryptocurrencies from the world's leading crypto exchanges. Sign up for a free, unlimited API key at [BlockMarkets Cryptocurrency API](https://www.blockmarkets.io/cryptocurrency-api).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BlockMarkets;

/**
 * ModelEmptyTest Class Doc Comment
 *
 * @category    Class
 * @description ModelEmpty
 * @package     BlockMarkets
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ModelEmptyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ModelEmpty"
     */
    public function testModelEmpty()
    {
    }
}
