<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BlockMarkets
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BlockMarkets Cryptocurrency API
 *
 * The BlockMarkets API provides real-time and historical market data on cryptocurrencies from the world's leading crypto exchanges. Sign up for a free, unlimited API key at [BlockMarkets Cryptocurrency API](https://www.blockmarkets.io/cryptocurrency-api).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BlockMarkets;

use \BlockMarkets\Configuration;
use \BlockMarkets\ApiException;
use \BlockMarkets\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  BlockMarkets
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for benchmarkRate
     *
     * Returns the latest available benchmark rates for a specific asset..
     *
     */
    public function testBenchmarkRate()
    {
    }

    /**
     * Test case for benchmarkRateHistory
     *
     * Returns historical benchmark rates for an asset. Requires premium subscription..
     *
     */
    public function testBenchmarkRateHistory()
    {
    }

    /**
     * Test case for listAssetMarkets
     *
     * Returns a list of all markets (base and quote) for a specific asset..
     *
     */
    public function testListAssetMarkets()
    {
    }

    /**
     * Test case for listAssets
     *
     * Returns a list of supported assets..
     *
     */
    public function testListAssets()
    {
    }

    /**
     * Test case for listBenchmarkRates
     *
     * Returns a list of supported USD benchmark rates..
     *
     */
    public function testListBenchmarkRates()
    {
    }

    /**
     * Test case for listExchangeMarkets
     *
     * Returns a list of markets for a specific exchange..
     *
     */
    public function testListExchangeMarkets()
    {
    }

    /**
     * Test case for listExchanges
     *
     * Returns a list of supported exchanges..
     *
     */
    public function testListExchanges()
    {
    }

    /**
     * Test case for listMarkets
     *
     * Returns a list of supported markets..
     *
     */
    public function testListMarkets()
    {
    }

    /**
     * Test case for listPairMarkets
     *
     * Returns a list of markets for a specific asset pair..
     *
     */
    public function testListPairMarkets()
    {
    }

    /**
     * Test case for listPairs
     *
     * Returns a list of supported asset pairs..
     *
     */
    public function testListPairs()
    {
    }

    /**
     * Test case for listSpotRates
     *
     * Returns a list of supported USD spot rates..
     *
     */
    public function testListSpotRates()
    {
    }

    /**
     * Test case for marketBook
     *
     * Returns the top 50 bids and asks from the current order book for a market pair. Requires premium subscription..
     *
     */
    public function testMarketBook()
    {
    }

    /**
     * Test case for marketOHLCV
     *
     * Returns OHLCV history for a market pair..
     *
     */
    public function testMarketOHLCV()
    {
    }

    /**
     * Test case for marketTicker
     *
     * Returns the latest ticker for a market pair..
     *
     */
    public function testMarketTicker()
    {
    }

    /**
     * Test case for marketTrades
     *
     * Returns trades for a market pair. Requires premium subscription..
     *
     */
    public function testMarketTrades()
    {
    }

    /**
     * Test case for spotRate
     *
     * Returns the last USD spot rate for an asset..
     *
     */
    public function testSpotRate()
    {
    }

    /**
     * Test case for spotRateHistory
     *
     * Returns historical spot rates for an asset. Requires premium subscription..
     *
     */
    public function testSpotRateHistory()
    {
    }

    /**
     * Test case for spotRateOHLCV
     *
     * Returns the OHLCV history for a spot rate..
     *
     */
    public function testSpotRateOHLCV()
    {
    }
}
